/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import kontrolor.KontrolerLogIn;
import login.panel.PanelInputTextFieldLogInPassword;
import login.panel.PanelInputTextFieldLoginusername;
import verifikator.login.VerifikatorLogInPassword;
import verifikator.login.VerifikatorLogInUsername;

/**
 *
 * @author filip_000
 */
public class LoginForma extends javax.swing.JDialog implements ActionListener{

    /**
     * Creates new form LoginForma
     */
    
    public LoginForma(java.awt.Frame parent, boolean modal) throws Exception {
        super(parent, modal);

        initComponents();
        srediSvePanele();
        setValidator();
        //proslediUneteVrednostiValidatoru();
        btnLogIn.setMnemonic(KeyEvent.VK_ENTER);
        btnLogIn.setActionCommand("potvrdi");
        btnLogIn.addActionListener((ActionListener) this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelUnosPodataka = new javax.swing.JPanel();
        btnLogIn = new javax.swing.JButton();
        panelInputTextFieldLoginusername1 = new login.panel.PanelInputTextFieldLoginusername();
        panelInputTextFieldLogInPassword1 = new login.panel.PanelInputTextFieldLogInPassword();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("[CSGO] Login form\n");
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanelUnosPodataka.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Data entry"));

        btnLogIn.setText("Log In");
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });

        panelInputTextFieldLogInPassword1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                panelInputTextFieldLogInPassword1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelUnosPodatakaLayout = new javax.swing.GroupLayout(jPanelUnosPodataka);
        jPanelUnosPodataka.setLayout(jPanelUnosPodatakaLayout);
        jPanelUnosPodatakaLayout.setHorizontalGroup(
            jPanelUnosPodatakaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUnosPodatakaLayout.createSequentialGroup()
                .addGroup(jPanelUnosPodatakaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelUnosPodatakaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelUnosPodatakaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(panelInputTextFieldLogInPassword1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelInputTextFieldLoginusername1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanelUnosPodatakaLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(btnLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelUnosPodatakaLayout.setVerticalGroup(
            jPanelUnosPodatakaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUnosPodatakaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelInputTextFieldLoginusername1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelInputTextFieldLogInPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanelUnosPodataka, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed
        boolean flag = true;
        try {
            proslediUneteVrednostiValidatoru();
            if (PanelInputTextFieldLogInPassword.konacanPassword == true && PanelInputTextFieldLoginusername.konacanUsername == true) {
                JOptionPane.showMessageDialog(this, "Successful login", "Success", JOptionPane.INFORMATION_MESSAGE);
                KontrolerLogIn.getInstance().ugasiPocetnuFormu();
                
                MasterForma forma = new MasterForma((Frame) getParent(), true);
                forma.srediPanelSlike();
            } else {
                JOptionPane.showMessageDialog(this, "Failed login!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            Logger.getLogger(LoginForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLogInActionPerformed

    private void panelInputTextFieldLogInPassword1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_panelInputTextFieldLogInPassword1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelInputTextFieldLogInPassword1KeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogIn;
    private javax.swing.JPanel jPanelUnosPodataka;
    private login.panel.PanelInputTextFieldLogInPassword panelInputTextFieldLogInPassword1;
    private login.panel.PanelInputTextFieldLoginusername panelInputTextFieldLoginusername1;
    // End of variables declaration//GEN-END:variables

    private void srediSvePanele() {
        srediPanel(panelInputTextFieldLoginusername1, "Username", "", "");
        srediPanel(panelInputTextFieldLogInPassword1, "Password", "", "");
    }

    private void srediPanel(PanelInputTextFieldLogInPassword panel, String text, String value, String error) {
        panel.setText(text);
        panel.setValue(value);
        panel.setError(error);
    }

    private void srediPanel(PanelInputTextFieldLoginusername panel, String text, String value, String error) {
        panel.setText(text);
        panel.setValue(value);
        panel.setError(error);
    }

    private void setValidator() {
        panelInputTextFieldLoginusername1.setValidator(new VerifikatorLogInUsername());
        panelInputTextFieldLogInPassword1.setValidator(new VerifikatorLogInPassword());
    }

    private void proslediUneteVrednostiValidatoru() throws Exception {
        String username = panelInputTextFieldLoginusername1.getValue().toString();
        String password = panelInputTextFieldLogInPassword1.getValue().toString();
    }

    @Override
    public void actionPerformed(ActionEvent ae) {
        if ("enter".equals(ae.getActionCommand())) {
            btnLogIn.doClick();
        }
    }


}
