/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JPanel;
import kontrolor.KontrolerLogIn;

/**
 *
 * @author filip_000
 */
public class MasterForma extends javax.swing.JDialog {

    private static MasterForma instance;
    public static MasterForma getInstance(){
        if (instance == null) {
            instance = new MasterForma(new javax.swing.JFrame(), true);
        }
        return instance;
    }
    
    /**
     * Creates new form MasterForma
     */
    public MasterForma(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    private JPanel createBackgroundPanel() {
        return new JPanel() {
            BufferedImage image = null;
            {
                try {
                    image = ImageIO.read(getClass().getResource("mainMenu.jpg"));
                } catch (IOException ex) {
                    Logger.getLogger(TestBackgroundResize.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            }
            
            @Override
            public Dimension getPreferredSize() {
                return new Dimension(500, 500);
            }
        };
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        AdministracijaTimova = new javax.swing.JMenu();
        UnosTimova = new javax.swing.JMenuItem();
        IzmenaTimova = new javax.swing.JMenuItem();
        BrisanjeTimova = new javax.swing.JMenuItem();
        PretragaTimova = new javax.swing.JMenuItem();
        AdministracijaTurnira = new javax.swing.JMenu();
        UnosTurnira = new javax.swing.JMenuItem();
        PretragaTurnira = new javax.swing.JMenuItem();
        BrisanjeTurnira = new javax.swing.JMenuItem();
        IzmenaTurnira = new javax.swing.JMenuItem();
        UnosRezultata = new javax.swing.JMenu();
        OAplikaciji = new javax.swing.JMenu();
        LogOut = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("[CSGO] Main Menu");
        setPreferredSize(getMaximumSize());

        AdministracijaTimova.setText("Administracija Timova");

        UnosTimova.setText("Unos Timova");
        UnosTimova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnosTimovaActionPerformed(evt);
            }
        });
        AdministracijaTimova.add(UnosTimova);

        IzmenaTimova.setText("Izmena Timova");
        IzmenaTimova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IzmenaTimovaActionPerformed(evt);
            }
        });
        AdministracijaTimova.add(IzmenaTimova);

        BrisanjeTimova.setText("Brisanje Timova");
        AdministracijaTimova.add(BrisanjeTimova);

        PretragaTimova.setText("Pretraga timova");
        PretragaTimova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PretragaTimovaActionPerformed(evt);
            }
        });
        AdministracijaTimova.add(PretragaTimova);

        jMenuBar1.add(AdministracijaTimova);

        AdministracijaTurnira.setText("Administracija Turnira");

        UnosTurnira.setText("Unos Turnira");
        AdministracijaTurnira.add(UnosTurnira);

        PretragaTurnira.setText("Pretraga Turnira");
        AdministracijaTurnira.add(PretragaTurnira);

        BrisanjeTurnira.setText("Brisanje Turnira");
        AdministracijaTurnira.add(BrisanjeTurnira);

        IzmenaTurnira.setText("Izmena Turnira");
        AdministracijaTurnira.add(IzmenaTurnira);

        jMenuBar1.add(AdministracijaTurnira);

        UnosRezultata.setText("Unos Rezultata");
        jMenuBar1.add(UnosRezultata);

        OAplikaciji.setText("O Aplikaciji");
        jMenuBar1.add(OAplikaciji);

        LogOut.setText("Log Out");
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });
        jMenuBar1.add(LogOut);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 966, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 501, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UnosTimovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnosTimovaActionPerformed
        try {
            UnosTimova ut = new UnosTimova(new JFrame(), true, true);
            ut.setLocationRelativeTo(null);
            ut.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(MasterForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_UnosTimovaActionPerformed

    private void IzmenaTimovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IzmenaTimovaActionPerformed
        try {
            IzmenaTimova it = new IzmenaTimova(new JFrame(), true);
            it.setLocationRelativeTo(null);
            it.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(MasterForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_IzmenaTimovaActionPerformed

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        KontrolerLogIn.getInstance().vratiFormu();
    }//GEN-LAST:event_LogOutActionPerformed

    private void PretragaTimovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PretragaTimovaActionPerformed
      JDialog dialog = new PretrragaTimova(null, true);
      dialog.pack();
      dialog.setLocationRelativeTo(null);
      dialog.setVisible(true);
      
    }//GEN-LAST:event_PretragaTimovaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AdministracijaTimova;
    private javax.swing.JMenu AdministracijaTurnira;
    private javax.swing.JMenuItem BrisanjeTimova;
    private javax.swing.JMenuItem BrisanjeTurnira;
    private javax.swing.JMenuItem IzmenaTimova;
    private javax.swing.JMenuItem IzmenaTurnira;
    private javax.swing.JMenu LogOut;
    private javax.swing.JMenu OAplikaciji;
    private javax.swing.JMenuItem PretragaTimova;
    private javax.swing.JMenuItem PretragaTurnira;
    private javax.swing.JMenu UnosRezultata;
    private javax.swing.JMenuItem UnosTimova;
    private javax.swing.JMenuItem UnosTurnira;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

    public void srediPanelSlike() {
        MasterForma frame = getInstance();
        frame.setContentPane(createBackgroundPanel());
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xSize = tk.getScreenSize().width;
        int ySize = tk.getScreenSize().height;
        frame.setSize(xSize, ySize);
        
        
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }
}
