/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.OpstiDomenskiObjekat;
import domen.Turnir;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import kontroler.GUIKontroler;
import table.model.TournamentTable;

/**
 *
 * @author filip_000
 */
public class Tournament extends javax.swing.JDialog {

    /**
     * Creates new form Tournament
     */
    public Tournament(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        srediTextFieldSignedIn();
        popuniTabelu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFieldSignedUser = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaTournament = new javax.swing.JTable();
        btnNaprednaPretraga = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnObrisiSelektovanTurnir = new javax.swing.JButton();
        btnUbaciNoviTurnir = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("[CSGO] Tournament Administration");

        jLabel7.setText("Signed in user:");

        tabelaTournament.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaTournament);

        btnNaprednaPretraga.setText("Advanced Search");

        jButton2.setText("Change a selected Tournament");

        btnObrisiSelektovanTurnir.setText("Delete a selected Tournament");

        btnUbaciNoviTurnir.setText("Insert a new Tournament");

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtFieldSignedUser, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnClose)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 452, Short.MAX_VALUE)
                        .addComponent(btnUbaciNoviTurnir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnObrisiSelektovanTurnir)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(btnNaprednaPretraga)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel7))
                    .addComponent(txtFieldSignedUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNaprednaPretraga)
                    .addComponent(jButton2)
                    .addComponent(btnObrisiSelektovanTurnir)
                    .addComponent(btnUbaciNoviTurnir)
                    .addComponent(btnClose))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        int rez = JOptionPane.showConfirmDialog(this, "Are You sure that you want to quit?", "Info", JOptionPane.YES_NO_OPTION);
        if (rez == JOptionPane.YES_OPTION) {
            setVisible(false);
        }
    }//GEN-LAST:event_btnCloseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnNaprednaPretraga;
    private javax.swing.JButton btnObrisiSelektovanTurnir;
    private javax.swing.JButton btnUbaciNoviTurnir;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaTournament;
    private javax.swing.JTextField txtFieldSignedUser;
    // End of variables declaration//GEN-END:variables

    private void srediTextFieldSignedIn() {
        if (txtFieldSignedUser.getText().isEmpty()) {
            txtFieldSignedUser.setText(GUIKontroler.getInstance().postaviUlogovanogKorisnika());
            txtFieldSignedUser.setEditable(false);
        }
    }

    private void popuniTabelu() {
        ArrayList<Turnir> spisakTurnira = new ArrayList<>();
        try {
            ArrayList<OpstiDomenskiObjekat> list = GUIKontroler.getInstance().vratiListu(new Turnir());
            for (OpstiDomenskiObjekat opstiDomenskiObjekat : list) {
                spisakTurnira.add((Turnir) opstiDomenskiObjekat);
            }
            TournamentTable tableModel = new TournamentTable(spisakTurnira);
            tabelaTournament.setModel(tableModel);
        } catch (Exception ex) {
            Logger.getLogger(UnosTimova.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
