/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login.panel;

import verifikator.login.IValidator;

/**
 *
 * @author filip_000
 */
public class PanelInputTextFieldLoginusername extends javax.swing.JPanel implements IGetValue{

    public static boolean konacanUsername = false;
    private IValidator validator;
    /**
     * Creates new form PanelInputTextFieldLogin
     */
    public PanelInputTextFieldLoginusername() {
        initComponents();
    }
    
    public void setText(String text){
        jlabelText.setText(text);
    }
    
    public void setValue(String value){
        jtxtValue.setText(value);
    }
    
    public void setError(String error){
        jlabelError.setText(error);
    }
    
    public void setValidator (IValidator validator){
        this.validator = validator;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlabelText = new javax.swing.JLabel();
        jtxtValue = new javax.swing.JTextField();
        jlabelError = new javax.swing.JLabel();

        jlabelText.setText("jLabel1");

        jlabelError.setForeground(new java.awt.Color(255, 0, 0));
        jlabelError.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jlabelError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlabelText)
                        .addGap(33, 33, 33)
                        .addComponent(jtxtValue, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabelText)
                    .addComponent(jtxtValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jlabelError)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public Object getValue() throws Exception {
        if(validator != null){
            try{
                boolean flag = false;
                flag = validator.validate(jtxtValue.getText().trim());
                if (flag == false) {
                    jlabelError.setText("Username is not valid.");
                    
                }else{
                    jlabelError.setText("");
                    konacanUsername = true;
                }
            }catch(Exception ex){
                throw new Exception("Error!");
            }
        }
        return jtxtValue.getText().trim();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlabelError;
    private javax.swing.JLabel jlabelText;
    private javax.swing.JTextField jtxtValue;
    // End of variables declaration//GEN-END:variables
}
